name: "Hello Actions"
description: "Greet someone"
author: "your-email@example.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.MY_NAME }}


branding:
  icon: "mic"
  color: "purple"
