name: Default Variable 

on:
  push:
    branches: [main]

jobs:
  Default-Variable:
    runs-on: ubuntu-latest
    steps:
      - name: Display Default Variable
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "SHA: $GITHUB_SHA"
          echo "Event Name: $GITHUB_EVENT_NAME"
