name: Environment Variable example

on:
  push:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      APP_MODE: ${{ vars.APP_MODE }}

    steps:
      - name: Display Environment Variable
        run: echo "This is $APP_MODE mode"
