name: Hello World Workflow

# Trigger: Runs whenever you push code to the main branch
on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Hello from GitHub Actions 🚀"
