name: Manual input passing Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Description for param1'
        required: true
        default: 'Hello World'

jobs:
  runs-manual-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Manual trigger info
        run: |
          echo "This workflow was triggered manually with param1: ${{ github.event.inputs.param1 }}"
