name: Publishing to GitHub Container Registry

on:
  push:
    branches: [main]

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hello:latest
          docker build . --tag $IMAGE_NAME
          docker push $IMAGE_NAME
