name: Publish to GitHub Package

on:
  push:
    branches: [main]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: my-js-action

      - name: Build Package
        run: npm run build || echo "no build step"
        working-directory: my-js-action

      - name: Pack the app
        run: npm pack
        working-directory: my-js-action

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: my-js-action/*.tgz

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build_and_package
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Set up Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@haveyoumetmiz'

      - name: Configure npm
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
