name: Self-hosted runner

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  connect:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
