name: Test Hello Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./   # Use the action in the current repo
        with:
          MY_NAME: Miz
